[workspace]
resolver = "2"
members = [
    "examples/form",
    "examples/hello_world",
    "examples/layers",
    "examples/path_parameters",
    "examples/server_sent_events",
    "examples/state",
    "examples/web_sockets"
]
exclude = [
    "examples/hello_world_embassy",
]

[package]
name = "picoserve"
version = "0.1.2"
authors = ["Samuel Hicks"]
edition = "2021"
description = "An async no_std HTTP server suitable for bare-metal environments"
readme = "README.md"
repository = "https://github.com/sammhicks/picoserve"
license = "MIT"
keywords = ["no_std", "http", "web", "framework"]
categories = ["asynchronous", "network-programming", "web-programming::http-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = { version = "2.4.0", default-features = false }
embedded-io-async = "0.6.0"
futures-util = { version = "0.3.28", default-features = false }
heapless = { version = "0.7.16", features = ["serde"] }
lhash = { version = "1.0.1", features = ["sha1"] }
log = { version = "0.4.19", default-features = false }
ryu = "1.0.14"
serde = { version = "1.0.171", default-features = false, features = ["derive"] }
tokio = { version = "1.32.0", optional = true }

[features]
std = []
tokio = ["dep:tokio", "std", "serde/std"]
